# Generated by Django 3.1.5 on 2021-02-15 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210215_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
